version: "3.7"

services:
  app:
    container_name: rentx-api
    environment:
      APP_PORT: 3333
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3333:3333"
    volumes: 
      - .:/usr/app
