version: "3.7"

services:
  postgres-dev:
    container_name: postgres-dev
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rentx
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/postgres
  app:
    container_name: rentx-api
    environment:
      APP_PORT: 3333
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3333:3333"
    volumes: 
      - .:/usr/app
      - /usr/app/node_modules
    links:
      - postgres-dev
    depends_on: 
      - postgres-dev
volumes: 
  pgdata: 
    driver: local